language: generic

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build_and_push
      script:
        - docker build -t udagram-api-user ./udagram-api-user
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-frontend ./udagram-frontend
        - docker build -t udagram-reverseproxy ./udagram-reverseproxy
        - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
        - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
        - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1
        - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1.1
        - docker push $DOCKER_USERNAME/udagram-api-user:v1
        - docker push $DOCKER_USERNAME/udagram-api-feed:v1
        - docker push $DOCKER_USERNAME/udagram-frontend:v1
        - docker push $DOCKER_USERNAME/udagram-reverseproxy:v1.1
