apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: m7md2112/udagram-api-feed:v1.1
          ports:
            - containerPort: 3030
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
